import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const legacyDirectory = fileURLToPath(new URL('../rom/', import.meta.url));

// New ROMs are generated by hob-launcher and supplied as explicit build inputs.
// Existing historical fixtures remain readable without an override.
export async function readDemoRom(entry) {
  if (!/^[a-zA-Z0-9._-]+\.gb$/.test(entry.filename)) throw Error('Invalid demo ROM filename');
  const directory = process.env.HOB_DEMO_ROM_DIR || legacyDirectory;
  try {
    return await readFile(resolve(directory, entry.filename));
  } catch (error) {
    if (error.code === 'ENOENT') throw Error('Missing bounded ROM ' + entry.filename + '; set HOB_DEMO_ROM_DIR to the hash-bound hob-launcher output directory');
    throw error;
  }
}
